### ISSUE TITLE
Problema ao reabrir caixa de resposta

### ISSUE THREAD

**Issue by Secco2112** [guites/g#3]
ao clicar para fechar uma citação de resposta e clicar de novo pra abrir, ele não realiza esta última ação.

espero que ajustem, o site é muito bom, parabéins!

**Comment by guites** [comment]
ele não tava reabrindo a caixa de resposta pq o trigger era baseado na mudança de uma variável. como ela ficava salva, passar o mesmo valor não disparava a função. valeu!
